import type { ScanReport, AgentEntry, Vulnerability, SupplyChainIndicators } from '@opm/core';

function riskEmoji(score: number): string {
  if (score >= 70) return '🔴';
  if (score >= 40) return '🟡';
  return '🟢';
}

function riskBar(score: number): string {
  const filled = Math.round(score / 5);
  const empty = 20 - filled;
  return `${'█'.repeat(filled)}${'░'.repeat(empty)}`;
}

function formatIndicators(indicators: SupplyChainIndicators): string {
  const checks: Array<[keyof SupplyChainIndicators, string]> = [
    ['has_install_scripts', 'Install scripts'],
    ['has_native_bindings', 'Native bindings'],
    ['has_obfuscated_code', 'Obfuscated code'],
    ['has_network_calls', 'Network calls'],
    ['has_filesystem_access', 'Filesystem access'],
    ['has_process_spawn', 'Process spawning'],
    ['has_eval_usage', 'eval() usage'],
    ['accesses_env_variables', 'Environment variable access'],
  ];

  return checks
    .map(([key, label]) => `- ${indicators[key] ? '⚠️' : '✅'} ${label}`)
    .join('\n');
}

function formatVulnerabilities(vulns: Vulnerability[]): string {
  if (vulns.length === 0) return '*No vulnerabilities detected.*\n';

  return vulns.map((v, i) => {
    const sev = v.severity === 'HIGH' || v.severity === 'CRITICAL' ? '🔴' : v.severity === 'MEDIUM' ? '🟡' : '🟢';
    return [
      `**${sev} ${i + 1}. ${v.category}** (${v.severity})`,
      '',
      `> ${v.description}`,
      '',
      `- **File:** \`${v.file}\``,
      v.evidence ? `- **Evidence:** \`${v.evidence}\`` : '',
    ].filter(Boolean).join('\n');
  }).join('\n\n');
}

function formatAgent(agent: AgentEntry, index: number): string {
  const { result } = agent;
  const emoji = riskEmoji(result.risk_score);

  const modelLines = [`- **Model:** \`${agent.model}\``];
  if (agent.model_intelligence || agent.model_coding) {
    modelLines.push(`- **AI Intelligence Index:** ${agent.model_intelligence || '—'}/100 | **Coding Index:** ${agent.model_coding || '—'}/100 | **Weight:** ${agent.model_weight || '—'}`);
  }

  return [
    `### Agent ${index + 1}: \`${agent.agent_id}\``,
    '',
    ...modelLines,
    `- **Risk Score:** ${emoji} **${result.risk_score}/100** (${result.risk_level})`,
    `- **Recommendation:** ${result.recommendation}`,
    '',
    '#### Analysis',
    '',
    result.reasoning,
    '',
    '#### Supply Chain Indicators',
    '',
    formatIndicators(result.supply_chain_indicators),
    '',
    '#### Vulnerabilities',
    '',
    formatVulnerabilities(result.vulnerabilities),
    '',
    '#### Version Analysis',
    '',
    `- **Version reviewed:** ${result.version_analysis.version_reviewed}`,
    result.version_analysis.previous_versions_reviewed.length > 0
      ? `- **Previous versions:** ${result.version_analysis.previous_versions_reviewed.join(', ')}`
      : '',
    `- **Changelog risk:** ${result.version_analysis.changelog_risk}`,
    result.version_analysis.changelog_reasoning
      ? `- ${result.version_analysis.changelog_reasoning}`
      : '',
  ].filter(Boolean).join('\n');
}

export function formatReportAsMarkdown(report: ScanReport): string {
  const emoji = riskEmoji(report.aggregate_risk_score);
  const timestamp = new Date(report.scan_timestamp).toLocaleString('en-US', {
    dateStyle: 'long',
    timeStyle: 'short',
  });

  const sections = [
    `# ${emoji} OPM Security Report`,
    '',
    `## ${report.package}@${report.version}`,
    '',
    `- **Package:** ${report.package}`,
    `- **Version:** ${report.version}`,
    `- **Scanned:** ${timestamp}`,
    `- **Versions analyzed:** ${report.versions_analyzed.join(', ')}`,
    `- **Agents:** ${report.agents.length}`,
    '',
    '---',
    '',
    '## Aggregate Risk (Intelligence-Weighted)',
    '',
    `\`${riskBar(report.aggregate_risk_score)}\` **${report.aggregate_risk_score}/100** — ${report.consensus}`,
    '',
    `> Scores are weighted by each model's AI Intelligence and Coding indices from [Artificial Analysis](https://artificialanalysis.ai).`,
    '',
    report.aggregate_risk_score < 40
      ? '> ✅ This package appears safe based on multi-agent consensus.'
      : report.aggregate_risk_score < 70
        ? '> ⚠️ This package has medium risk indicators. Review the agent findings below.'
        : '> 🚨 This package has HIGH risk. Installation is not recommended.',
    '',
    '---',
    '',
    '## Agent Reports',
    '',
    ...report.agents.map((agent, i) => formatAgent(agent, i)),
    '',
    '---',
    '',
    '## Raw JSON',
    '',
    '```json',
    JSON.stringify(report, null, 2),
    '```',
    '',
    '---',
    '',
    `*Report generated by [OPM](https://github.com/dhananjaypai08/opm) — On-chain Package Manager*`,
  ];

  return sections.join('\n');
}
