import type { ScanReport, AgentEntry, Vulnerability, SupplyChainIndicators, CheckReport } from '@opm/core';

function riskEmoji(score: number): string {
  if (score >= 70) return '🔴';
  if (score >= 40) return '🟡';
  return '🟢';
}

function riskBar(score: number): string {
  const filled = Math.round(score / 5);
  const empty = 20 - filled;
  return `${'█'.repeat(filled)}${'░'.repeat(empty)}`;
}

function formatIndicators(indicators: SupplyChainIndicators): string {
  const checks: Array<[keyof SupplyChainIndicators, string]> = [
    ['has_install_scripts', 'Install scripts'],
    ['has_native_bindings', 'Native bindings'],
    ['has_obfuscated_code', 'Obfuscated code'],
    ['has_network_calls', 'Network calls'],
    ['has_filesystem_access', 'Filesystem access'],
    ['has_process_spawn', 'Process spawning'],
    ['has_eval_usage', 'eval() usage'],
    ['accesses_env_variables', 'Environment variable access'],
  ];

  return checks
    .map(([key, label]) => `- ${indicators[key] ? '⚠️' : '✅'} ${label}`)
    .join('\n');
}

function formatVulnerabilities(vulns: Vulnerability[]): string {
  if (vulns.length === 0) return '*No vulnerabilities detected.*\n';

  return vulns.map((v, i) => {
    const sev = v.severity === 'HIGH' || v.severity === 'CRITICAL' ? '🔴' : v.severity === 'MEDIUM' ? '🟡' : '🟢';
    return [
      `**${sev} ${i + 1}. ${v.category}** (${v.severity})`,
      '',
      `> ${v.description}`,
      '',
      `- **File:** \`${v.file}\``,
      v.evidence ? `- **Evidence:** \`${v.evidence}\`` : '',
    ].filter(Boolean).join('\n');
  }).join('\n\n');
}

function formatAgent(agent: AgentEntry, index: number): string {
  const { result } = agent;
  const emoji = riskEmoji(result.risk_score);

  const modelLines = [`- **Model:** \`${agent.model}\``];
  if (agent.model_intelligence || agent.model_coding) {
    modelLines.push(`- **AI Intelligence Index:** ${agent.model_intelligence || '—'}/100 | **Coding Index:** ${agent.model_coding || '—'}/100 | **Weight:** ${agent.model_weight || '—'}`);
  }

  return [
    `### Agent ${index + 1}: \`${agent.agent_id}\``,
    '',
    ...modelLines,
    `- **Risk Score:** ${emoji} **${result.risk_score}/100** (${result.risk_level})`,
    `- **Recommendation:** ${result.recommendation}`,
    '',
    '#### Analysis',
    '',
    result.reasoning,
    '',
    '#### Supply Chain Indicators',
    '',
    formatIndicators(result.supply_chain_indicators),
    '',
    '#### Vulnerabilities',
    '',
    formatVulnerabilities(result.vulnerabilities),
    '',
    '#### Version Analysis',
    '',
    `- **Version reviewed:** ${result.version_analysis.version_reviewed}`,
    result.version_analysis.previous_versions_reviewed.length > 0
      ? `- **Previous versions:** ${result.version_analysis.previous_versions_reviewed.join(', ')}`
      : '',
    `- **Changelog risk:** ${result.version_analysis.changelog_risk}`,
    result.version_analysis.changelog_reasoning
      ? `- ${result.version_analysis.changelog_reasoning}`
      : '',
  ].filter(Boolean).join('\n');
}

export function formatReportAsMarkdown(report: ScanReport): string {
  const emoji = riskEmoji(report.aggregate_risk_score);
  const timestamp = new Date(report.scan_timestamp).toLocaleString('en-US', {
    dateStyle: 'long',
    timeStyle: 'short',
  });

  const sections = [
    `# ${emoji} OPM Security Report`,
    '',
    `## ${report.package}@${report.version}`,
    '',
    `- **Package:** ${report.package}`,
    `- **Version:** ${report.version}`,
    `- **Scanned:** ${timestamp}`,
    `- **Versions analyzed:** ${report.versions_analyzed.join(', ')}`,
    `- **Agents:** ${report.agents.length}`,
    '',
    '---',
    '',
    '## Aggregate Risk (Intelligence-Weighted)',
    '',
    `\`${riskBar(report.aggregate_risk_score)}\` **${report.aggregate_risk_score}/100** — ${report.consensus}`,
    '',
    `> Scores are weighted by each model's AI Intelligence and Coding indices from [Artificial Analysis](https://artificialanalysis.ai).`,
    '',
    report.aggregate_risk_score < 40
      ? '> ✅ This package appears safe based on multi-agent consensus.'
      : report.aggregate_risk_score < 70
        ? '> ⚠️ This package has medium risk indicators. Review the agent findings below.'
        : '> 🚨 This package has HIGH risk. Installation is not recommended.',
    '',
    '---',
    '',
    '## Agent Reports',
    '',
    ...report.agents.map((agent, i) => formatAgent(agent, i)),
    '',
    '---',
    '',
    '## Raw JSON',
    '',
    '```json',
    JSON.stringify(report, null, 2),
    '```',
    '',
    '---',
    '',
    `*Report generated by [OPM](https://github.com/dhananjaypai08/opm) — On-chain Package Manager*`,
  ];

  return sections.join('\n');
}

export function formatCheckReportAsMarkdown(report: CheckReport): string {
  const timestamp = new Date(report.timestamp).toLocaleString('en-US', {
    dateStyle: 'long', timeStyle: 'short',
  });

  const typosquats = report.deps.filter((d) => d.typosquat);
  const cveBlocked = report.deps.filter((d) => d.cveCritical > 0);
  const cveWarned = report.deps.filter((d) => d.cveCount > 0 && d.cveCritical === 0);
  const highRisk = report.deps.filter((d) => d.onChainScore !== null && d.onChainScore >= 70);
  const safeCount = report.totalDeps - typosquats.length - cveBlocked.length - cveWarned.length - highRisk.length;

  const sections: string[] = [
    `# OPM Dependency Check Report`,
    '',
    `- **Project:** ${report.project}`,
    `- **Scanned:** ${timestamp}`,
    `- **Total dependencies:** ${report.totalDeps}`,
    '',
    '---',
    '',
    '## Summary',
    '',
    `| Category | Count |`,
    `|---|---|`,
    `| ${typosquats.length > 0 ? '🔴' : '🟢'} Typosquats | ${typosquats.length} |`,
    `| ${cveBlocked.length > 0 ? '🔴' : '🟢'} Critical CVEs | ${cveBlocked.length} |`,
    `| ${cveWarned.length > 0 ? '🟡' : '🟢'} CVE Warnings | ${cveWarned.length} |`,
    `| ${highRisk.length > 0 ? '🔴' : '🟢'} High On-chain Risk | ${highRisk.length} |`,
    `| 🟢 Safe | ${Math.max(0, safeCount)} |`,
    '',
  ];

  if (typosquats.length > 0) {
    sections.push('---', '', '## Typosquat Risks', '');
    for (const d of typosquats) {
      sections.push(
        `### \`${d.name}\`@${d.version}`,
        '',
        `- **Likely intended package:** \`${d.typosquat!.likelyTarget}\``,
        `- **Confidence:** ${d.typosquat!.confidence}`,
        `- **Reason:** ${d.typosquat!.reason}`,
        '',
      );
    }
  }

  if (cveBlocked.length > 0) {
    sections.push('---', '', '## Critical Vulnerabilities', '');
    for (const d of cveBlocked) {
      sections.push(
        `### \`${d.name}\`@${d.version}`,
        '',
        `- **Critical:** ${d.cveCritical} | **High:** ${d.cveHigh}`,
        `- **CVEs:** ${d.cveIds.join(', ')}`,
        d.fixVersion ? `- **Fix:** upgrade to \`${d.fixVersion}\`` : '',
        '',
      );
    }
  }

  if (cveWarned.length > 0) {
    sections.push('---', '', '## CVE Warnings', '');
    for (const d of cveWarned) {
      sections.push(
        `- \`${d.name}\`@${d.version} — ${d.cveCount} CVE(s)${d.fixVersion ? ` → \`${d.fixVersion}\`` : ''}`,
      );
    }
    sections.push('');
  }

  if (highRisk.length > 0) {
    sections.push('---', '', '## High On-chain Risk', '');
    for (const d of highRisk) {
      sections.push(`- \`${d.name}\`@${d.version} — risk score **${d.onChainScore}/100**`);
    }
    sections.push('');
  }

  if (report.agents.length > 0) {
    sections.push('---', '', '## AI Agent Analysis', '');
    for (const a of report.agents) {
      const flags = a.findings.filter((f) => f.issue !== 'safe' && f.severity !== 'NONE');
      sections.push(
        `### \`${a.agentId}\` — ${a.model}`,
        '',
        `- **AI Intelligence:** ${a.intelligence}/100 | **Coding:** ${a.coding}/100`,
        `- **Risk Score:** ${a.riskScore}/100`,
        '',
      );
      if (flags.length > 0) {
        for (const f of flags) {
          sections.push(
            `- **[${f.severity}]** \`${f.package}\` — ${f.issue}: ${f.explanation}` +
            (f.suggested_replacement ? ` → \`${f.suggested_replacement}\`` : ''),
          );
        }
      } else {
        sections.push(`- ✅ No issues found`);
      }
      sections.push('', `> ${a.overall}`, '');
    }
  }

  sections.push(
    '---',
    '',
    `*Report generated by [OPM](https://github.com/dhananjaypai08/opm) — On-chain Package Manager*`,
  );

  return sections.filter((l) => l !== undefined).join('\n');
}
